### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by nYCSTs** [cryzed/TrafficToll#10]
I sent you a message in your reddit, but since i dont know if you check it frequently i decided to ask for help here, hope that you dont mind.

So thats what i did:
1) pip3 install traffictoll
2) added to the path: "PATH=~/.local/bin/:$PATH" at the end of .bashrc
3) downloaded and edited your "example.yaml", trying to limit Brave download speed.
4) finally, i runt "tt esp3o0 example.yaml" (sudo tt ... gives me a "command not found")
Here, im getting an error: "Missing dependency: Executable for command: 'tc qdisc add dev esp3o0 handle ffff: ingress' not found"

![ajOHGl0](https://user-images.githubusercontent.com/63932475/90983641-03a77900-e546-11ea-9177-6f0fd83c34c6.png)

For now on i dont know what to do. 
I tried to install trafic controll (apt-get install iproute2) but it is already installed. 
I also tried to run "$tc qdisc add dev esp3o0 handle ffff: ingress".

Please help me, your program will be extremely useful for me. I also would like to ask: where is the .yaml file supposed to be located?

**Comment by cryzed** [comment]
> Here, im getting an error: "Missing dependency: Executable for command: 'tc qdisc add dev esp3o0 handle ffff: ingress' not found"

~~Can you run `$ which tc` on your system? If Debian's iproute2 doesn't ship with `tc` for some reason, you'll have to figure out which package in Debian provides it and install it, otherwise TrafficToll can't work.~~

EDIT: A friend just informed that in Debian the `PATH` for the root user is slightly different and includes `/usr/sbin`, which is where the `tc` executable is located on your system. So the solution comes down to switching your effective user using `su` or installing sudo and running TrafficToll as explained in the README.

> finally, i runt "tt esp3o0 example.yaml" (sudo tt ... gives me a "command not found")

If `sudo tt ...` gives you an error, then you also need to install sudo or switch to your root user (`su`) and run `tt` instead. But this is more general Linux knowledge, not specific to TrafficToll.

> I also would like to ask: where is the .yaml file supposed to be located?

The path you specify is relative to the current working directory.

**Comment by nYCSTs** [comment]
Ok, i managed to make it work, but i've some questions.

> EDIT: A friend just informed that in Debian the `PATH` for the root user is slightly different and includes `/usr/sbin`, which is where the `tc` executable is located on your system. So the solution comes down to switching your effective user using `su` or installing sudo and running TrafficToll as explained in the README.

Sorry about that, i installed Debian yesterday so i didnt know about it.
What do you mean with switching my effective user?
About sudo, i already have it installed

`sudo --version`
`Sudo version 1.8.27`


> If `sudo tt ...` gives you an error, then you also need to install sudo or switch to your root user (`su`) and run `tt` instead. But this is more general Linux knowledge, not specific to TrafficToll.

As i said, i already have sudo installed. When i tried to use su i got "module not found" with logoru, ruamel.yaml and psutil. After installing them with pip3 i got the same error as before.


The environment is still kinda new to me, so maybe my solution isn't the best, but what i did was:

`sudo env "PATH=$PATH" tt enp3s0 example.yaml`  

I've 2 main questions:
~~1) Sorry for my lack of knowledge here, but can you help me in setting the sudo environment so i don't need to type `env "PATH=$PATH"` every time. I tried setting the sudoers with visudo but i was not successful.~~

Ok, i did the obvious: sudo pip3 install traffictoll

2) The point here is editing .yaml according to what program i want to limit the download/upload speed. Do you have any recommended task manager to easily see the correct path for every currently opened program? Searching through previous issues i found a print from a task manager that you were using ([https://github.com/cryzed/TrafficToll/issues/1#issuecomment-462166294](url)), what is the name of it?

**Comment by cryzed** [comment]
> Do you have any recommended task manager to easily see the correct path for every currently opened program?

That was KSysGuard, usually bundled with the KDE Plasma desktop.

Regarding the rest of your comment: I'm sorry but I don't know what's going on with your Debian installation, I can't help you with that. You have to find a way to install TrafficToll and then execute `tt` as the root user. How exactly you install TrafficToll (virtual environment, `pip3 install ... --user`, package etc.) and then execute it (`sudo`, `su`, login as `root` etc.) is up to you.
