### ISSUE TITLE
OSS Compliance

### ISSUE THREAD

**Issue by SatzzRam** [cryzed/TrafficToll#11]
I liked your traffic toll application. But I can't use it due to Oss compliance. Would you change it to GPLv2 License, so that this application will be used.

**Comment by cryzed** [comment]
I am curious: what is the difference between GPLv2 and GPLv3 that would allow TrafficToll to be used by either you, your company, or "many companies"?

**Comment by SatzzRam** [comment]
As per the GPLv3 License, if any companies use any GPLv3 licensed software for commercial purposes then they have to make their whole code base open-source.

**Comment by cryzed** [comment]
Hey sorry, but I won't be adjusting the license to something more permissive. I used the GPL for a reason.
