### ISSUE TITLE
user error?

### ISSUE THREAD

**Issue by Reaper176** [cryzed/TrafficToll#12]
I have been using this for a while now. Grate bit of kit btw. Recently tho i have suddenly started getting the error.
`Traceback (most recent call last):
  File "/home/john/.local/bin/tt", line 5, in <module>
    from traffictoll.__main__ import main
ModuleNotFoundError: No module named 'traffictoll'

`
I am not sure what i did to break it. I uninstalled and made sure it was removed, cleaned up and reinstalled. However the error persists. Would anyone be able to offer some kind of insight into what i might have done to bork this? Your help is much appriciated.

**Comment by cryzed** [comment]
Hey, can you let me know what operating system you are using and how you installed TrafficToll? It looks like despite installing it, it's not found on your Python search path. I suspect it might be related to the recent update from Python 3.9 to Python 3.10; Are you using Arch Linux?

**Comment by sigmaSd** [comment]
If you're using `paru`  you need to pass `--rebuild` flag

**Comment by Reaper176** [comment]
I am using arch, or more specifically garuda linux. I did pip3 install traffictoll.

**Comment by cryzed** [comment]
Please tell me the exact command you used to install TrafficToll, including which user. Did you use `sudo`?

**Comment by cryzed** [comment]
@Reaper176 any more feedback on this?

**Comment by slrslr** [comment]
Can this be reopened, i am getting same error on Debian 11 $ pip3 --version
pip 20.3.4 from /usr/lib/python3/dist-packages/pip (python 3.9)
```

pip3 install traffictoll
cd;echo -e "download: 60mbit\nupload: 60mbit\ndownload-minimum: 1mbit\nupload-minimum: 1mbit" > test.yaml
sudo /home/$(whoami)/.local/bin/tt wg0 test.yaml --delay 0.5
```

if i do not use sudo, then the error is:

```
2022-02-18 22:46:20.522 | INFO     | traffictoll.cli:main:146 - Setting up global class with max download rate: 60mbit (minimum: 1mbit) and priority: 0
2022-02-18 22:46:20.522 | INFO     | traffictoll.cli:main:168 - Setting up global class with max upload rate: 60mbit (minimum: 1mbit) and priority: 0
RTNETLINK answers: Operation not permitted
modprobe: ERROR: could not insert 'ifb': Operation not permitted
2022-02-18 22:46:20.541 | ERROR    | traffictoll.__main__:main:25 - Unexpected error occurred:
Traceback (most recent call last):
  File "/home/user/.local/bin/tt", line 8, in <module>
    sys.exit(main())
    │   │    └ <function main at 0x7f25ce902040>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
> File "/home/user/.local/lib/python3.9/site-packages/traffictoll/__main__.py", line 17, in main
    cli_main(arguments)
    │        └ Namespace(device='wg0', config='test.yaml', delay=0.5, logging_level='INFO', speed_test=False)
    └ <function main at 0x7f25cdc38700>
  File "/home/user/.local/lib/python3.9/site-packages/traffictoll/cli.py", line 183, in main
    ingress_qdisc, egress_qdisc = tc_setup(
                                  └ <function tc_setup at 0x7f25cdc38310>
  File "/home/user/.local/lib/python3.9/site-packages/traffictoll/tc.py", line 138, in tc_setup
    ifb_device = _acquire_ifb_device()
                 └ <function _acquire_ifb_device at 0x7f25cdc380d0>
  File "/home/user/.local/lib/python3.9/site-packages/traffictoll/tc.py", line 68, in _acquire_ifb_device
    return _create_ifb_device()
           └ <function _create_ifb_device at 0x7f25cdc38040>
  File "/home/user/.local/lib/python3.9/site-packages/traffictoll/tc.py", line 48, in _create_ifb_device
    name = after.difference(before).pop()
           │     │          └ {'lo', 'wg0', 'enx00e04c3926c3'}
           │     └ <method 'difference' of 'set' objects>
           └ {'lo', 'wg0', 'enx00e04c3926c3'}

KeyError: 'pop from an empty set'
2022-02-18 22:46:20.545 | INFO     | traffictoll.tc:_clean_up:31 - Cleaning up IFB device
rmmod: ERROR: Module ifb is not currently loaded
```

Thank you in advance

**Comment by sigmaSd** [comment]
Sometimes error like these happen if you have updated your kernel and didn't restart, if this is the case restart your pc and try again

**Comment by slrslr** [comment]
I have just restarted and retry. No change. Reopen please.

**Comment by sigmaSd** [comment]
I just reread your comment, you have to use sudo, it won't work without it, if you're having the same issue as the user here the fix is to rebuild pip pkgs
`pip install --user --force-reinstall --ignore-installed --no-binary :all: traffictoll`

**Comment by slrslr** [comment]
Hello, thank you, but [that command/output ](https://bin.disroot.org/?e14d11ded16cd3f3#BdtU5dndKqU6W1WvJrCdwr7UmsScjeNMSm7AZrw91i5p)(pass.: tt) not fixed it. shows same errors..
