### ISSUE TITLE
Missing option to run on background / unable to change limit during runtime?

### ISSUE THREAD

**Issue by slrslr** [cryzed/TrafficToll#14]
README does not contain any detail how run the thing at background and change the limit during runtime.
I know this can be done on Linux, somehow but only part of people know how.

I am trying to launch the app at system b00t at background. I have clue how to do it.

Then during runtime change limit by using different yaml file. Here is a problem how to stop currently running tt.
I have tried:
`sudo pkill -f "/path/to/yaml";sudo tt eth0 "/path/to/file.yaml --delay 0.5 &`

yet it does not seem to be working well. When i trigger a bash script with that command, then it stays foreground and i can not reuse that terminal window.

It can be handy to add an switch that sends the app to background. --background
I wish i could then be able to replace current active yaml by different one, changing limits during runtime without the need to kill.

If you have any ideas how to solve this (run on background), thank you in advance.

**Comment by cryzed** [comment]
Hey, I'm sorry, but overall this is more of a Linux systems-administrations issue; I don't think it falls into TrafficToll's scope to fix this.
