### ISSUE TITLE
Missing dependency: Executable for command: 'tc qdisc add dev wg0 handle ffff: ingress' not found

### ISSUE THREAD

**Issue by slrslr** [cryzed/TrafficToll#15]
Hello,
please what should i do on Linux Debian stable so traffictoll-1.5.0 does not fail when launched as user?
```
INFO     | traffictoll.cli:main:146 - Setting up global class with max download rate: 60mbit (minimum: 1mbit) and priority: 2
INFO     | traffictoll.cli:main:168 - Setting up global class with max upload rate: 60mbit (minimum: 1mbit) and priority: 2
ERROR    | traffictoll.__main__:main:23 - Missing dependency: Executable for command: 'tc qdisc add dev wg0 handle ffff: ingress' not found
```
when i prefix tt command by "sudo " then "sudo: tt: command not found"
It was installed using pip3 command..

UPDATE: this was likely due to normal user not having /usr/sbin (where tc is located) in PATH. I could do following to add it:
```
export PATH=$PATH:/usr/sbin:/home/$(whoami)/.local/bin
echo "export PATH=$PATH:/usr/sbin:/home/$(whoami)/.local/bin" >> ~/.bashrc
```
then launch the tt using sudo prefix.

**Comment by slrslr** [comment]
Here the commands to reproduce this:
```
pip3 install traffictoll
cd;echo -e "download: 60mbit\nupload: 60mbit\ndownload-minimum: 1mbit\nupload-minimum: 1mbit" > test.yaml
/home/$(whoami)/.local/bin/tt wg0 test.yaml --delay 0.5
```

**Comment by sigmaSd** [comment]
You're probably missing tc, I think it comes with iproute2 packages

**Comment by cryzed** [comment]
Pretty much what @sigmaSd said, I'm surprised that Debian doesn't come with that package preinstalled.

**Comment by slrslr** [comment]
> missing tc

"pip3 install tc" [failed](https://bin.disroot.org/?e5bbb40bf0b7a783#7dRz7amx7fwNWE9qCjLnkK36uq5CtsSTkPAPa9YpD2JK), but "sudo apt install iproute2" said "iproute2 is already the newest version (5.10.0-4)."

$ whereis tc
`tc: /usr/sbin/tc /usr/lib/tc /usr/share/man/man8/tc.8.gz`

As mentioned, tt was installed by pip3 and location is /home/user/.local/bin/tt

Can you reopen this and suggest why tt errors?

**Comment by sigmaSd** [comment]
can you run `strace -o log /home/$(whoami)/.local/bin/tt wg0 test.yaml --delay 0.5` and upload the log

**Comment by slrslr** [comment]
yes, [here is the output](https://bin.disroot.org/?4530740f9b308922#2ZD12gaYRcNzYmQcyLmbfWuK51ycKgGTLW5WjWAPWgPr) (pass: tt)

**Comment by sigmaSd** [comment]
You can see from the last part of the log where it looks for tc, @cryzed maybe you should consider adding /usr/sbin to search path

**Comment by cryzed** [comment]
I don't think it's a good idea to arbitrarily check directories that are not part of the user's `PATH` variable. The better solution here is for @slrslr to adjust (or rather fix?) their system configuration and add `/usr/sbin` to their system `PATH` variable.
