### ISSUE TITLE
Installation problems with python-pip

### ISSUE THREAD

**Issue by ghost** [cryzed/TrafficToll#4]
I have installed python2 and python3, as well as python-pip

`$ pip install https://github.com/cryzed/TrafficToll/archive/master.zip`

Collecting https://github.com/cryzed/TrafficToll/archive/master.zip
  Downloading https://github.com/cryzed/TrafficToll/archive/master.zip
     | 71kB 878kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ImportError: No module named setuptools
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-hqZ08A-build/

**Comment by cryzed** [comment]
This means that your environment is missing the setuptools package, which is required for pip to work correctly.
