### ISSUE TITLE
AttributeError: 'Logger' object has no attribute '_levels'

### ISSUE THREAD

**Issue by megitu** [cryzed/TrafficToll#5]
TrafficToll stopped working.

In the past TrafficToll worked great when started with a command `sudo tt eno1 tt200.yaml`,
where the file tt200.yaml consist of:
```
# Global limits 
download: 200kbps
upload: 200kbps
```

**Now**, after a command `sudo tt eno1 tt200.yaml` (or even `sudo tt`) there is an error message:
```
Traceback (most recent call last):
  File "/usr/sbin/tt", line 11, in <module>
    load_entry_point('TrafficToll==0.1.0', 'console_scripts', 'tt')()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.8/site-packages/traffictoll/cli.py", line 19, in <module>
    argument_parser.add_argument('--logging-level', '-l', choices=logger._levels, default='INFO')
AttributeError: 'Logger' object has no attribute '_levels'

```

**Comment by cryzed** [comment]
Your version of Loguru is too recent -- the correct one should have been installed when you initially installed TrafficToll, something else (another project that shares the Python environment) or you, must have upgraded it.

I'll take a look at upgrading the Loguru dependency and making it compatible with the latest version soon.

**Comment by cryzed** [comment]
Actually, I think this is my fault. I never specified specific version in the `setup.py`, so Loguru got updated at some point and broke it. Please try reinstalling traffictoll using:

`pip install https://github.com/cryzed/TrafficToll/archive/master.zip --upgrade`

That should hopefully work.

**Comment by megitu** [comment]
After running your command there was an error message:
```
ERROR: Could not install packages due to an EnvironmentError: [Errno 13] No access: '/usr/bin/tt'
Consider using the `--user` option or check the permissions.
```
After adding `--user` (I hope in the right place) as below, I "Successfully installed traffictoll-0.1.0".
`pip install https://github.com/cryzed/TrafficToll/archive/master.zip --upgrade --user`

But still I have the same error (as in the first post) after starting tt.

And I am using the current [loguru 0.4.0 ](https://aur.archlinux.org/packages.php?ID=677646)

**Comment by cryzed** [comment]
How did you install traffictoll initially?

**Comment by megitu** [comment]
Installed in Manjaro Linux (based on Arch Linux) from [this package](https://aur.archlinux.org/packages/traffictoll/).

Edit:
And may be the Python version is a problem?
The current python, which I am using, is 3.8.1.
An as I see in the [code](https://github.com/cryzed/TrafficToll/commit/c802c41102c02a8821db7ad931565b7a19a079be) (though I am not a pyton developer) 
- in line 46: `python = "<3.8"`
- in line 56: `marker = "platform_python_implementation == \"CPython\" and python_version < \"3.8\""`

**Comment by megitu** [comment]
Now it seems OK, but I had to manually modify line 19 in the file `/usr/lib/python3.8/site-packages/traffictoll/cli.py` .

For reasons I do not know, after updating the TrafficToll package, the content of line 19 in this file was still the same as in the previous version, i.e.:
` argument_parser.add_argument('--logging-level', '-l', choices=logger._levels, default='INFO')`
and I had to manually change it to the current state:
`argument_parser.add_argument('--logging-level', '-l', choices=logger._core.levels, default='INFO')`

Thanks for the update.

**Comment by sigmaSd** [comment]
Hi, I updated the `aur` package, It should now keep up automatically with upstream updates.

**Comment by megitu** [comment]
Thanks, now the update is running smoothly, without errors.

**Comment by cryzed** [comment]
Thank you @sigmaSd, that's great. I had forgotten that TrafficToll has an AUR package.

**Comment by sigmaSd** [comment]
No problem @cryzed !
